### ISSUE TITLE
Unhandled Promise rejection on signIn

### ISSUE THREAD

**Issue by lcsoka** [CodetrixStudio/CapacitorGoogleAuth#11]
Hi there,

I'm trying to handle the case when the user interrupts the login process, cancels the login window or the authorization window, but it always throws an error.

I tried multiple ways to avoid this issue.

First i tried to put the await in a try-catch block.
```js
try {
let googleUser = await Plugins.GoogleAuth.signIn();
} catch (error) {
console.log('User interrupted the login process', error);
}
```
But it didn't work, because it threw this error
`
ERROR Error: Uncaught (in promise): Object: {"error":"popup_closed_by_user"}
`
Then i tried to catch it like a promise error.

```js
Plugins.GoogleAuth.signIn().then((googleUser)=>{
...
}).catch((error)=>{
console.log('User interrupted the login process', error);
})
```
This threw the same error as before.
EDIT:
This issue is present on WEB only, when i import the module, it gets imported on iOS too and all the methods get overridden.

Im guessing the signIn method misses an error catch here. 
https://github.com/CodetrixStudio/CapacitorGoogleAuth/blob/24a6e1ad6ee00ebb78b0dc10a12c3929e9d863ac/src/web.ts#L50

or here:
https://github.com/CodetrixStudio/CapacitorGoogleAuth/blob/24a6e1ad6ee00ebb78b0dc10a12c3929e9d863ac/src/web.ts#L47

**Comment by parveenkhtkr** [comment]
@lcsoka  It should now catch the error as you first tried in the version `1.1.2`
