### ISSUE TITLE
Request server auth code on android

### ISSUE THREAD

**Issue by macdja38** [CodetrixStudio/CapacitorGoogleAuth#12]
The following code in the init method is required to request the serverAuthCode on android
```java
        .requestServerAuthCode(serverClientId)
```

it can be chained into the builder like so
```java
                .requestIdToken(clientId)
                .requestServerAuthCode(clientId)
                .requestEmail();
```

Required to reach feature parody with https://github.com/CodetrixStudio/CapacitorGoogleAuth/issues/5 on iOS.

**Comment by parveenkhtkr** [comment]
Will add it @macdja38 
Will add an optional way to have all configuration at one place too, as I also see configuration being in too many places can be daunting.

**Comment by macdja38** [comment]
That would be awesome, I've yet to go through and try and consolidate all of our apps configuration stuff. But something that can eventually pull from environment variables in a build step would be best in my case at least.

**Comment by ronaldgrn** [comment]
Hey, looking forward to the android requestServerAuthCode change. 

Thanks for the great work so far @parveenkhtkr

**Comment by parveenkhtkr** [comment]
Added via #20 
version 1.2.1

**Comment by macdja38** [comment]
Not sure if I agree with putting config in the strings. Those seem to be for translations from what I can find?
