### ISSUE TITLE
Issue on Capacitor 3

### ISSUE THREAD

**Issue by iamkbkarthikeyan** [CodetrixStudio/CapacitorGoogleAuth#125]
Hi there,

I've capacitor 3 upgraded project. Google Auth is works well on web. For Android it throws,

`D/Capacitor: Sending plugin error: {"save":false,"callbackId":"126270162","pluginId":"GoogleAuth","methodName":"signIn","success":false,"error":{"message":"Something went wrong"}}`

I think currently it is not support for capacitor 3. Because there is no documentation for capacitor 3 (Android).
I need clarification on,
1. In Capacitor 3, There is no onCreate in MainActivity. So, We need to write it manually or not. Capacitor side they said, no need to import anything on mainActivity file.
2. It is support for android and iOS with Capacitor 3 ?
3. Everything is fine as per the docs. then why it shows something went wrong?

**Comment by NLueg** [comment]
I have the same issue. I can't use the plugin for Capacitor 3 on Android 😢

**Comment by iamkbkarthikeyan** [comment]
Hi, @NLueg.
I got white screen with Google Loading Spinner. It struck on auth.
If anyone Resolve this. Please post here.
Thanks in advance.

Versions we've used,
Angular : 12
Ionic : 5
Capacitor: 3

**Comment by Mersal-Mohamed** [comment]
i got the same problem and the solution is 

1 - in mani Activity i didn't add any thing 
`package com.peacetvnetwork.peacetv;

import com.getcapacitor.BridgeActivity;

public class MainActivity extends BridgeActivity {

    // Initializes the Bridge

}
`
2- I am just adding this line in strings.xml

    <string name="server_client_id">{your google id}</string>

3- adding my google-service.json in android app folder

and it's working good

**Comment by Mersal-Mohamed** [comment]
i forgot important issue 
this file 
android/app/src/assets/capacitor.config.json

should be like this 
{
	"appId": "com.peacetvnetwork.peacetv",
	"appName": "peace TV",
	"webDir": "www",
	"bundledWebRuntime": false,
	"plugins": {
		"GoogleAuth": {
			"scopes": [
				"profile",
				"email"
			],
			"serverClientId": "your id",
			"forceCodeForRefreshToken": true
		}
	}
}

dont forget to change appId, appname etc

**Comment by NLueg** [comment]
@Mersal-Mohamed are you sure, that you have the latest version of the plugin and use Capacitor 3?
The steps you mentioned are the initial configuration that this plugin works. It worked for me perfectly before I migrated to Capacitor 3 so I would say that my configuration is correct

**Comment by NLueg** [comment]
I found the problem. The android part wasn't migrated to Capacitor 3. Only iOS and web were migrated.
I will create a PR for this.

**Comment by iamkbkarthikeyan** [comment]
Hi Guys, 
@Mersal-Mohamed  @NLueg I think It may be Key mismatch. I just explain here. What exactly i am done.
1. I created a Firebase Project and I entered SHA1 Key
2. I enabled Google Authentication in Authentication Section
3. google-service.json File added in Android Folder
4. I used "WEB" Client key for capacitor.config.json and strings.xml

@Mersal-Mohamed  Please let me know. If anything wrong.

Thanks.

**Comment by NLueg** [comment]
@iamkbkarthikeyan I don't think that this is the case. A week ago (before I updated to Cap 3) everything works fine. After the migration (and without changing the config) the plugin doesn't work for Android.
This is because the Android part wasn't migrated to Cap 3.
