### ISSUE TITLE
Interface 'CapacitorInstance' incorrectly extends interface 'CapacitorGlobal'.

### ISSUE THREAD

**Issue by rajesh-5445** [CodetrixStudio/CapacitorGoogleAuth#130]
Ionic serve not working after installing GoogleAuth plugin.

Here is the error,
`
[ng] Error: node_modules/@codetrix-studio/capacitor-google-auth/node_modules/@capacitor/core/types/definitions-internal.d.ts:16:18 - error TS2430: Interface 'CapacitorInstance' incorrectly extends interface 'CapacitorGlobal'.
[ng]   Types of property 'Plugins' are incompatible.
[ng]     Property 'GoogleAuth' is missing in type '{ [pluginName: string]: { [prop: string]: any; }; }' but required in type 'PluginRegistry'.
[ng] 16 export interface CapacitorInstance extends CapacitorGlobal {
[ng]                     ~~~~~~~~~~~~~~~~~
[ng]   node_modules/@codetrix-studio/capacitor-google-auth/dist/esm/definitions.d.ts:4:9
[ng]     4         GoogleAuth: GoogleAuthPlugin;
[ng]               ~~~~~~~~~~
[ng]     'GoogleAuth' is declared here.
`

Here is my ionic info,
`
Ionic:
   Ionic CLI                     : 6.16.3 (/Users/***/.nvm/versions/node/v14.17.3/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.8
   @angular-devkit/build-angular : 0.1101.4
   @angular-devkit/schematics    : 11.2.13
   @angular/cli                  : 11.1.4
   @ionic/angular-toolkit        : 3.1.1

Capacitor:
   Capacitor CLI      : 2.4.7
   @capacitor/android : 2.4.7
   @capacitor/core    : 2.4.7
   @capacitor/ios     : 2.4.7

Cordova:
   Cordova CLI       : not installed
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:
   cordova-res : not installed globally
   native-run  : not installed globally

System:
   NodeJS : v14.17.3 (/Users/***/.nvm/versions/node/v14.17.3/bin/node)
   npm    : 6.14.13
   OS     : macOS Catalina
`

**Comment by cyril-colin** [comment]
Hi, I have the same problem on multiple plugin since capacitor 3, I put my response here : https://github.com/capacitor-community/firebase-crashlytics/issues/41#issuecomment-885676407

**Comment by cyril-colin** [comment]
linked to this, I guess : https://github.com/CodetrixStudio/CapacitorGoogleAuth/issues/106

**Comment by rajesh-5445** [comment]
Hi,

I had this fixed.
By removing the ^ in the capacitor core version.

**Comment by cyril-colin** [comment]
Hi, thanks for your response. However, the problem appears again after this change, and I don't understand how this change could fix the problem because it comes from the package.json plugin, not from my project's pachage.json.

Note, that this issue is a duplication of https://github.com/CodetrixStudio/CapacitorGoogleAuth/issues/105

**Comment by amalethia** [comment]
I have tried resolving this issue by changing the version to 3 like this in my package.json:
"@codetrix-studio/capacitor-google-auth": "3.0.0"
