### ISSUE TITLE
invalid_audience: The audience client and the client need to be in the same project on iPhone

### ISSUE THREAD

**Issue by metalllus** [CodetrixStudio/CapacitorGoogleAuth#135]
I have an Ionic 5/Capacitor 3 app built with Angular/FIrebase. The Google Auth login works perfectly fine on native Android. However on iPhone, after selecting the google account for login and being redirected back to the app I get this error message: invalid_audience: The audience client and the client need to be in the same project. In my capacitor.config.ts I have serverClientId key under GoogleAuth with value taken from GCP OAuth 2.0 Client IDs - Web client (auto created by Google Service) - Type Web Application. I have the reversed client id as an url scheme under URL schemes in Info.plist and the GoogleService-Info.plist under App/App. Any ideas what the problem might be?

**Comment by eugenek0110** [comment]
@metalllus  Did you find the reason? Same issue :/
