### ISSUE TITLE
removing profile scope

### ISSUE THREAD

**Issue by jonit-dev** [CodetrixStudio/CapacitorGoogleAuth#141]
Does this work without the "profile" scope on capacitor.config.json?

I tried removing this and it keeps asking for my profile info regardless.

Any clue why?

I've uninstalled the app, cleared Android Studio cache, etc.

**Comment by petnoterlabs** [comment]
Same issue. Does anyone have a solution other than trying a new plugin?

**Comment by manubenjamin** [comment]
Does anyone have a solution for this issue?

**Comment by reslear** [comment]
set clean "scopes": [],
