### ISSUE TITLE
bug ios: scopes not use

### ISSUE THREAD

**Issue by reslear** [CodetrixStudio/CapacitorGoogleAuth#144]
hi @joeflateau , It seems we forgot about `scopes` :)

https://github.com/CodetrixStudio/CapacitorGoogleAuth/blob/deaac21b0ac0dc3a39f8db4738751e59c09e1d97/ios/Plugin/Plugin.swift#L29-L31

discussion: 
- https://github.com/google/GoogleSignIn-iOS/issues/23
- https://github.com/google/GoogleSignIn-iOS/pull/30
 
I found several suggestions:
1. custom lib https://github.com/amieso/GoogleSignIn-iOS/pull/1
2. https://github.com/google/GoogleSignIn-iOS/issues/23#issuecomment-908244462

for test can use complete example https://github.com/reslear/CapacitorGoogleAuth-Vue3-example/tree/next

Could you try?

**Comment by joeflateau** [comment]
Oh yes. I guess I did. I should be able to address that tomorrow

**Comment by reslear** [comment]
@joeflateau cool, let's leave it that way for now
