### ISSUE TITLE
Ionic 5, Capacitor 3, Android 11: "something went wrong"

### ISSUE THREAD

**Issue by ciccilleju** [CodetrixStudio/CapacitorGoogleAuth#153]
hello,
i've just tested the plugin both on iOS and Android. 
iOS works just fine, no problems at all, Android acts weird:

i get this error:
 
![image](https://user-images.githubusercontent.com/42606234/135493637-92389e45-b5d5-4276-aed4-04c7ba5455df.png)

   Ionic CLI                     : 6.17.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.7.0
   @angular-devkit/build-angular : 12.2.4
   @angular-devkit/schematics    : 12.2.4
   @angular/cli                  : 12.2.4

I've already checked client_id and sha1 key

this is a video from me, getting the error: [VIDEO](https://www.dropbox.com/s/ypas78hjqdwpbh4/error%20google%20signin.mov)

what can I do to fix it?
thank you

 
![image](https://user-images.githubusercontent.com/42606234/135493737-1c64276d-0e47-4459-a88a-e735bf087ded.png)

**Comment by ciccilleju** [comment]
it was my mistake with the SHA1 key

**Comment by ciccilleju** [comment]
> How did you set up ??
> 
> Are you use AndroidClinet ? not WebClient ?
> 
> plz see #157

using webclient it works but if I upload the .aab file on the Play Store, it doesnt work anymore.
If I make the APK from android studio, it works, if i use .aab, it doesnt.

**Comment by sawaca96** [comment]
I think you should use [Play App signing](https://ionic.zendesk.com/hc/en-us/articles/4404813713175-Play-App-Signing-for-AAB-in-google-play-console) because App on Play Store change fingerprint

**Comment by ciccilleju** [comment]
Perfect! Its working, thank you so much

Il Lun 15 Nov 2021, 01:17 Song ***@***.***> ha scritto:
