### ISSUE TITLE
Release 3.1 to npm

### ISSUE THREAD

**Issue by adam-h** [CodetrixStudio/CapacitorGoogleAuth#155]
It seems like release 3.1 was created ([here](https://github.com/CodetrixStudio/CapacitorGoogleAuth/commit/cc598f29b5ac99d7e35f54e022597cfb0835a7cd)) but not published to `npm`.

Is it possible to push that up?

**Comment by reslear** [comment]
https://github.com/CodetrixStudio/CapacitorGoogleAuth/pull/142#issuecomment-913578531

**Comment by adelabd** [comment]
+1
