### ISSUE TITLE
ERROR Error: Uncaught (in promise): Error: Something went wrong 

### ISSUE THREAD

**Issue by MJAVTDEV** [CodetrixStudio/CapacitorGoogleAuth#165]
Hi,

I have used this plugin for authentication for calendar API. 
My project Env:
   Ionic CLI                     : 6.18.0 
   Ionic Framework               : @ionic/angular 6.0.1
   @angular-devkit/build-angular : 13.0.4
   @angular-devkit/schematics    : 13.0.4
   @angular/cli                  : 13.0.4
   @ionic/angular-toolkit        : 5.0.3
   
   
Capacitor:

   Capacitor CLI      : 3.3.3
   @capacitor/android : 3.3.3
   @capacitor/core    : 3.3.3
   @capacitor/ios     : not installed

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 1.5.0

System:

   NodeJS : v14.17.6 
   npm    : 6.14.15

When I click on auth screen and select user after that I get this error.
capacitor.config.json
 "plugins": {
        "GoogleAuth": {
            "scopes": ["profile", "email"],
            "androidClientId": "324318******-*****9cab5pbh**-*******rvfcj*-***.apps.googleusercontent.com",
            "forceCodeForRefreshToken": false
        }
    }

**Comment by reslear** [comment]
need add to scopes calendar api scope
