### ISSUE TITLE
iOS Build Fails With Errors

### ISSUE THREAD

**Issue by dalezak** [CodetrixStudio/CapacitorGoogleAuth#17]
After adding `@codetrix-studio/capacitor-google-auth` plugin, the iOS build now fails with the errors:

**Plugin.swift:110:23: Use of undeclared type 'GIDSignInUIDelegate'**
<img width="958" alt="Screenshot 2019-08-29 15 50 55" src="https://user-images.githubusercontent.com/91811/63978979-fc55a880-ca74-11e9-8f22-cbbddeeccd3b.png">

**Plugin.swift:21:9: Value of type 'GIDSignIn' has no member 'uiDelegate'; did you mean 'delegate'?**
<img width="926" alt="Screenshot 2019-08-29 15 49 25" src="https://user-images.githubusercontent.com/91811/63979043-273ffc80-ca75-11e9-898a-fd2cc90db348.png">

**Plugin.swift:39:21: Value of type 'GIDSignIn' has no member 'hasAuthInKeychain'**
**Plugin.swift:40:22: Value of type 'GIDSignIn' has no member 'signInSilently'**
<img width="932" alt="Screenshot 2019-08-29 15 50 00" src="https://user-images.githubusercontent.com/91811/63978999-0b3c5b00-ca75-11e9-8569-331a85aa566f.png">

**Plugin.swift:73:53: Extra argument 'sourceApplication' in call**
<img width="903" alt="Screenshot 2019-08-29 15 50 25" src="https://user-images.githubusercontent.com/91811/63979068-3de65380-ca75-11e9-902a-e5801e44d1f5.png">

**Comment by parveenkhtkr** [comment]
@dalezak please try version 1.2.0, it should be fixed.
Feel free to reopen if not.
