### ISSUE TITLE
Always get "popup_closed_by_user" on Web

### ISSUE THREAD

**Issue by josephchow102** [CodetrixStudio/CapacitorGoogleAuth#18]
After I choose a Google account and then continue, the popup closed itself and then get the error "popup_closed_by_user".

I am using version 1.1.2

**Comment by parveenkhtkr** [comment]
Couldn't reproduce this on my end.
Any pointers?

**Comment by parveenkhtkr** [comment]
I was able to reproduce it, accompanied by an error message above it, which is self-explanatory.
Feel free to reopen if it's something else.

<img width="656" alt="Screenshot 2019-10-25 at 1 31 28 AM" src="https://user-images.githubusercontent.com/6024312/67520833-40f16f00-f6c7-11e9-9dc9-576484aed1c0.png">
