### ISSUE TITLE
Does it support for using GoogleAuth.signOut()

### ISSUE THREAD

**Issue by whitersun** [CodetrixStudio/CapacitorGoogleAuth#184]
I watched docs from github does not found any line to say about google sign Out, so I try find it from definitions.d.ts and found this one 

![image](https://user-images.githubusercontent.com/37898596/156024062-da7caa44-43a2-4756-82b0-1cb27f118959.png)

After found the signOut Api option and try to use on browser and after test I realized the Oauth2 token was not deleted from localStorage of my browser. So I am confuse does it the bug or just not support to use?

**Comment by reslear** [comment]
support 
https://github.com/CodetrixStudio/CapacitorGoogleAuth/blob/4d05537005a7b1f505901f2e842fb70712138527/src/web.ts#L122-L124
