### ISSUE TITLE
[Android] Google Sign In webview does not redirect back to app

### ISSUE THREAD

**Issue by Berkodev** [CodetrixStudio/CapacitorGoogleAuth#19]
Hi, 

I'm trying to add Google authentication to my Capacitor app. I followed the tutorial on the repo, the Google Sign In webview is being opened, however upon successful login, it switches to "One moment please..." and it  never closes the webview or goes back to the app.

The android:launchMode in my manifest is currently set to "singleTask", and I tried "singleInstance" as well.

When tested on web, the authentication worked properly (popup window was closed and I got the accessToken back).

Would appreciate help in trying to solve this. Thanks!

**Comment by nicolasrhone** [comment]
Same issue here

**Comment by parveenkhtkr** [comment]
I have included a demo project if you can reproduce it there please reopen the issue with steps and maybe something can be done about it.

**Comment by rohilv** [comment]
Having same issue

**Comment by ManuelIgnacioRoca** [comment]
Same issue here, has anyone found any solution? i tried using the GoogleAuth event but even with that i wasn't able to fetch the userChange event and it redirects to me to an empty page (still in chrome)

**Comment by epicshaggy** [comment]
When I first installed the plugin it worked great, I tried it out again to test it before moving on and it works on web and ios, but i get redirected to a blank webview after selecting an account.
