### ISSUE TITLE
"GoogleAuth" plugin is not implemented on ios.

### ISSUE THREAD

**Issue by pogularakesh** [CodetrixStudio/CapacitorGoogleAuth#191]
While trying to implement sign in with google in ios getting "GoogleAuth" plugin is not implemented on ios.(Works fine in android device).

**Comment by kevinpallado** [comment]
@pogularakesh 

Did you get any results after signing in android device?

**Comment by pogularakesh** [comment]
@kevinpallado  Yes getting token in android device.

**Comment by reslear** [comment]
incorrectly installed capacitor
