### ISSUE TITLE
java.lang.NegativeArraySizeException: -1

### ISSUE THREAD

**Issue by incal** [CodetrixStudio/CapacitorGoogleAuth#204]
Hi,
I have this error in AndroidStudio debug:

`    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.etarom.xxxxxx/io.ionic.starter.MainActivity}: java.lang.NegativeArraySizeException: -1
....
....
Caused by: java.lang.NegativeArraySizeException: -1
        at com.codetrixstudio.capacitor.GoogleAuth.GoogleAuth.load(GoogleAuth.java:71)`

I checked the configurations and I don't seem to have forgotten anything, any suggestions?

regards

**Comment by incal** [comment]
my fault I did not understand the configuration instructions for using it with ionic

**Comment by awesaman** [comment]
Could you clarify how you fixed your configuration? Thanks

**Comment by incal** [comment]
Hi,
in my values/string.xml file was missing the 'app_client_id'

`<?xml version='1.0' encoding='utf-8'?>
<resources>
.......
    <string name="server_client_id">xxxxx-xxxxx.apps.googleusercontent.com</string>
    <string name="app_client_id">434308698913-rrrqijq1jk0hbe2qarfh8dpd9rfbrmr4.apps.googleusercontent.com</string>
</resources>`

i put in xml file both configurations: 'server_client_id' and 'app_client_id'

**Comment by RamallahS** [comment]
@awesaman 
> Could you clarify how you fixed your configuration? Thanks

I had this issue and fix it (from instuctions):

Provide configuration in root capacitor.config.json
{
  "plugins": {
    "GoogleAuth": {
      "scopes": ["profile", "email"],
      "serverClientId": "xxxxxx-xxxxxxxxxxxxxxxxxx.apps.googleusercontent.com",
      "forceCodeForRefreshToken": true
    }
  }
}

**Comment by incal** [comment]
@awesaman's suggestion is correct, I set google settings in both string.xml and capacitor.config.json file

**Comment by awesaman** [comment]
Thank you both. Both of these suggestions had to be taken into account, and I had forgotten to change the capacitor.config.json. Now my project is working, but it's very slow on android, unfortunately. Let me know if yall had the same issue. I'm considering migrating to Google Identity Services.

**Comment by incal** [comment]
i am using the google auth plugin in an Ionic Capacitor project; in my case the execution of Android in emulators is very slow, while in physical devices I do not experience particular slowness

**Comment by Samerkassem** [comment]
I put them in both files:

```
<?xml version='1.0' encoding='utf-8'?>
<resources>
    <string name="app_name">Jobly</string>
    <string name="title_activity_main">Jobly</string>
    <string name="package_name">com.samk.jobly</string>
    <string name="custom_url_scheme">com.samk.jobly</string>
    <string name="server_client_id">xxxxxxxxx.apps.googleusercontent.com</string> 
<string name="app_client_id">xxxxxxx.xapps.googleusercontent.com</string>
</resources>

```

(both app_client_id and server_client_id have same value, is that wrong?)
and in :


```

{
  "server": {
    "url": "http://192.168.2.203:8100",
    "originalUrl": "http://192.168.2.203:8100"
  },
  "plugins": {
    "GoogleAuth": {
      "scopes": [
        "profile",
        "email"
      ],
      "serverClientId": "xxxxxxx.apps.googleusercontent.com"
    }
  }
}
```

And still getting the same exact error as OP

**Comment by incal** [comment]
> I put them in both files:
> 
> ```
> <?xml version='1.0' encoding='utf-8'?>
> <resources>
>     <string name="app_name">Jobly</string>
>     <string name="title_activity_main">Jobly</string>
>     <string name="package_name">com.samk.jobly</string>
>     <string name="custom_url_scheme">com.samk.jobly</string>
>     <string name="server_client_id">xxxxxxxxx.apps.googleusercontent.com</string> 
> <string name="app_client_id">xxxxxxx.xapps.googleusercontent.com</string>
> </resources>
> ```
> 
> (both app_client_id and server_client_id have same value, is that wrong?) and in :
> 
> ```
> 
> {
>   "server": {
>     "url": "http://192.168.2.203:8100",
>     "originalUrl": "http://192.168.2.203:8100"
>   },
>   "plugins": {
>     "GoogleAuth": {
>       "scopes": [
>         "profile",
>         "email"
>       ],
>       "serverClientId": "xxxxxxx.apps.googleusercontent.com"
>     }
>   }
> }
> ```
> 
> And still getting the same exact error as OP

Hi, yes I use the same value for app_client_id and server_client_id

**Comment by MuffinMan82** [comment]
Nothing worked, i can assure you. the only solution was to remove the plugin.

**Comment by fletcherist** [comment]
working config
```ts
const config: CapacitorConfig = {
  appId: 'com.lfg.app',
  appName: 'lfg',
  webDir: 'out',
  bundledWebRuntime: false,
  plugins: {
    GoogleAuth: {
      serverClientId:
        'xxx-xxx.apps.googleusercontent.com',
      androidClientId:
        'xxx-xxx.apps.googleusercontent.com',
      scopes: ['profile', 'email'],
    },
  },
};
```

strings.xml has no capacitor-google-auth fields

the problem is at GoogleAuth.java
```java
// 71 line
Scope[] scopes = new Scope[scopeArray.length - 1];
```
is passed empty scopes, it panics and crashes with that error

**Comment by fletcherist** [comment]
> I'm so sorry you can't get it to work. My working configuration is:
> 
> `.. "plugins": { "GoogleAuth": { "scopes": ["profile", "email"], "serverClientId": "xxxxxx.apps.googleusercontent.com", "androidClientId": "xxxxxx.apps.googleusercontent.com", "forceCodeForRefreshToken": true } .... } ... `
> 
> package version:
> 
> `..... "@capacitor/android": "4.5.0", "@capacitor/core": "^4.5.0", "@capacitor/ios": "^4.5.0", "@codetrix-studio/capacitor-google-auth": "^3.2.0", .....`

yeah after adding `"scopes": ["profile", "email"]` to capacitor json config it works, thanks for that issue

**Comment by samerkassem82** [comment]
> > I'm so sorry you can't get it to work. My working configuration is:
> > `.. "plugins": { "GoogleAuth": { "scopes": ["profile", "email"], "serverClientId": "xxxxxx.apps.googleusercontent.com", "androidClientId": "xxxxxx.apps.googleusercontent.com", "forceCodeForRefreshToken": true } .... } ... `
> > package version:
> > `..... "@capacitor/android": "4.5.0", "@capacitor/core": "^4.5.0", "@capacitor/ios": "^4.5.0", "@codetrix-studio/capacitor-google-auth": "^3.2.0", .....`
> 
> yeah after adding `"scopes": ["profile", "email"]` to capacitor json config it works, thanks for that issue

But isn't this what I already did? please read my original post.

**Comment by samerkassem82** [comment]
This is what I put in the root of project in capacitor.config.json (yes, I put xxxxx for screenshot only), in the root of the angular project, not the android folder

![image](https://user-images.githubusercontent.com/40912775/213664052-5c4bb333-983c-470d-a9d8-383cc9d69005.png)


but when I do $ ionic capacitor sync android , the stuff is not being copied to the capacitor.config.json in android/app/src/main/assets
![image](https://user-images.githubusercontent.com/40912775/213664654-f333220b-cc35-4af1-bbd3-a1062aba70b3.png)

Yet, the plugin appears here:

![image](https://user-images.githubusercontent.com/40912775/213664761-95349cbe-dc28-42b6-99d6-73cadb7d23f1.png)


NOT MATTER WHAT I DO,  i get this error:

![image](https://user-images.githubusercontent.com/40912775/213664893-67759301-3cec-4523-b3ce-2e80f712a517.png)

**Comment by incal** [comment]
Hello,
the thing is very strange. is this message present during in sync?:

![Screenshot 2023-01-20 alle 10 46 46](https://user-images.githubusercontent.com/7112614/213666751-db847a1b-eeb0-435c-a044-93dca607c1f1.png)

your "server" config section also looks different to me in the capacitor.config.json file in android/app/src/main/assets,  in my project they are identical

**Comment by incal** [comment]
if you add something like this in your root capacitor.config.json
`"PushNotifications": {
		"presentationOptions": ["badge", "sound", "alert"]
	  },`

is it reported in android platform file?

**Comment by fletcherist** [comment]
> but when I do $ ionic capacitor sync android , the stuff is not being copied to the capacitor.config.json in
idk but maybe you should try this one `npx cap sync android`? it works for me, but maybe it's just an alias for `ionic capacitor sync android`

**Comment by samerkassem82** [comment]
Do you know what made it work???

![image](https://user-images.githubusercontent.com/40912775/213675500-80387720-9ef0-4c40-8aad-7592c85ffba1.png)



By adding to JAVA initiate values for this damned scoped array

![image](https://user-images.githubusercontent.com/40912775/213675640-0aa10113-cc16-42fd-801f-010e87646411.png)


NOTHING ELSE WORKED FOR ME.

@fletcherist I will try your suggestions later, this is a hobbyist project

**Comment by kunalchikte** [comment]
If you have created the capacitor.config.json file in the root of the project then you have to remove the capacitor.config.ts file from the project, because while creating an android project it generates the config file with the reference of the ts file and not from json file.
