### ISSUE TITLE
Generating New Access Token After Being Expired

### ISSUE THREAD

**Issue by dalezak** [CodetrixStudio/CapacitorGoogleAuth#22]
The authentication is working great for me in browser and on iOS, however after the `access_token` expires, I start getting `invalid_token` when making requests to Google's API. Is there a way to refresh the `access_token`?

Looking at the source, it appears only [signIn()](https://github.com/CodetrixStudio/CapacitorGoogleAuth/blob/247c7c34fb57224e05da4a9174c857096b286abd/src/web.ts#L41) and [signOut](https://github.com/CodetrixStudio/CapacitorGoogleAuth/blob/247c7c34fb57224e05da4a9174c857096b286abd/src/web.ts#L89) are implemented. However looks like you're calling `await googleUser.reloadAuthResponse();` in `signIn`. Would exposing this as a method help generate a new `access_token`?

**Comment by dalezak** [comment]
@parveenkhtkr here's a [PR](https://github.com/CodetrixStudio/CapacitorGoogleAuth/pull/23) which adds a `resignIn` method to force `googleUser.reloadAuthResponse()`.  Would this help for expired `access_token`? /cc @matheo

**Comment by matheo** [comment]
@dalezak can this be integrated into `signIn` when the response is `invalid_token`?
It feels good when you don't have to worry and the plugin takes care of that condition.

**Comment by dalezak** [comment]
That's a good idea @matheo, maybe @parveenkhtkr has a better idea how that might be implemented?

**Comment by parveenkhtkr** [comment]
Will have it integrated.

**Comment by dalezak** [comment]
@parveenkhtkr when the `access_token` expires, I'm re-calling `signIn` however it's prompting the user again to accept app permissions. 

Is there a way to silently re-authenticate without prompting the user again?

**Comment by scriptPilot** [comment]
Is there any planning to let the plugin manage the refresh in the background? It would be great to have a callback whenever there is a token update in order to save the updated token to the application store :-)

**Comment by parveenkhtkr** [comment]
@dalezak `refresh()` API is now exposed in v1.4.0 for Web and iOS
I don't know the call for Android if somebody can point me to the API I can add it too.

**Comment by parveenkhtkr** [comment]
@scriptPilot can add it probably, open it up in the new issue.

**Comment by scriptPilot** [comment]
Done - many thanks for your quick response :-)
