### ISSUE TITLE
Migrate to Google Identity (from Google Sign In)

### ISSUE THREAD

**Issue by jamesrgrace** [CodetrixStudio/CapacitorGoogleAuth#225]
Google is requiring migration to use Google Identity Services instead of Google Sign in by March 31, 2023.

[https://developers.google.com/identity/gsi/web/guides/migration#popup-mode](url)

Is it possible to update this library to support Google Identity?

**Comment by Epameinondas-Theodoropoulos** [comment]
I was ready to write the same. This is important I think

**Comment by reslear** [comment]
PR welcome

**Comment by reslear** [comment]
duplicate #202
