### ISSUE TITLE
Error: Something went wrong only on one Android device

### ISSUE THREAD

**Issue by davidecampello** [CodetrixStudio/CapacitorGoogleAuth#230]
Hi guys! We are using this plugin into an app and all is working fine except for a user that reported that he can't login with his google account. He is using android 12 with LE2123 device (I think one plus) with 4-5 google accounts connected.
I tried with some  android devices (only emulated) and It's working fine.
He sent me [this video](https://youtube.com/shorts/F7OXitH60mY?feature=share) that show what he see.
I released a version with Setry to chek the errors and this is what i can see:
<img width="513" alt="image" src="https://user-images.githubusercontent.com/21193922/196732613-5463b0c9-8afc-47ae-be81-65a1268dbf64.png">

this is a public link to sentry error. I don't think there are all the informations about the error but In case in can provide some screenshot.
[https://sentry.io/share/issue/a645f82efd2e485b9266d4964cfbc30d/](url)

Thanks for your help!

**Comment by IssaYor** [comment]
![image](https://user-images.githubusercontent.com/87547387/196815379-ab01c596-3028-459a-803d-6cac5c3884e2.png)

**Comment by IssaYor** [comment]
> ![image](https://user-images.githubusercontent.com/87547387/196815379-ab01c596-3028-459a-803d-6cac5c3884e2.png)

The same happened to me

**Comment by sajath-45** [comment]
same here

**Comment by davidecampello** [comment]
I solved my issue. It turned out that trying only on emulator I was using an unsigned version of the bundle and the google service.json had only the sha1 of the unsigned version.
Using the correct sha1 (i got it from google play) and the new google services.json all is working fine.
Thanks
