### ISSUE TITLE
CodetrixStudioCapacitorGoogleAuth/Plugin.swift:65: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value

### ISSUE THREAD

**Issue by DacostaDesarrollo** [CodetrixStudio/CapacitorGoogleAuth#239]
Hi, I'm Daniel, what is causing this error, I don't know what I'm doing wrong, could you please guide me

<img width="1440" alt="Captura de Pantalla 2022-11-25 a la(s) 2 11 30 p m" src="https://user-images.githubusercontent.com/3371350/204051675-c91e50f2-edd0-485d-bca6-c2548e2371f8.png">

**Comment by djaramilloj** [comment]
Having same error here

**Comment by DacostaDesarrollo** [comment]
I already found a solution, I needed to create "OAuth client ID" and import the updated GoogleService-Info.plist file to my project in xcode, remember that the OAuth client ID must be created pointing to the ios application type
