### ISSUE TITLE
Callback on any token update 

### ISSUE THREAD

**Issue by scriptPilot** [CodetrixStudio/CapacitorGoogleAuth#26]
It would be great to have a callback whenever there is a token update (at startup and later) in order to save the updated token to the application store :-)

**Comment by parveenkhtkr** [comment]
@scriptPilot v1.5.0 provides a listener for user change. If there's more to token update/change please point me to docs.
It's only for web, will be adding support for iOS & Android too.

**Comment by scriptPilot** [comment]
Cool, thanks :-)
