### ISSUE TITLE
DOCS ISSUE: Error code 10 in Capacitor 4 with Google Auth in Android

### ISSUE THREAD

**Issue by j-d-carmichael** [CodetrixStudio/CapacitorGoogleAuth#263]
We are using Capacitor v4.7.0

We use Firebase for push notifications (https://capacitorjs.com/docs/guides/push-notifications-firebase)

We use Google and Facebook for SSO on the web and have had no issues before and after starting to integrate Google SSO in the app.

In fact, the Facebook (https://github.com/capacitor-community/facebook-login) login is integrated into our Android app just fine.

We're getting dizzy running through all the rabbit warrens of guides....

**Issue/Question 1: For Google SSO to work with this plugin, do we need to use Firebase?** 

A lot of the SO posts and other guides point to using Firebase for SSO - but this makes no sense to us as we have our own server for authentication, and it works fine for Google SSO via our web app. We just passed a token to google from the client and all is good.

**Issue/Question 2: Do we have to wait for the new Android OAuth to be approved?**

When we added the Android OAuth key, we noticed that the google OAuth consent screen changed; we now have " Verification in progress"  again. So, we're hoping it is just this, but Google is not helpful in any way there to know what is what.

____________________________

We spent a good number of hours trying to get this to work, but we only seem to be able to get in return error #10 without any further info from Google.

We have done the following to try and get this to work:

1. Added the SHA1 to our firebase Push Notification project.
2. Added the android OAuth key and the server id to the capacitor.ts file as illustrated here: https://github.com/CodetrixStudio/CapacitorGoogleAuth/#configure
3. Added all the android code and js code
4. But... nothing works - we only get error 10.

**Comment by j-d-carmichael** [comment]
We solved this crazy issue!

The key was getting the client ID from the google-services.json file, which is actually the client ID for firebase and nothing mentioned in any Google OAuth!!!

On Firebase itself, head to build -> authentication, then on the signing method tab you have to add Google as an additional provider.

Then magically is just worked! 

There was no mentioned on this in these docs, or Google docs... just a series of trial and error and digging through other issues. Completely mad.

**Comment by j-d-carmichael** [comment]
The issue here is that this should be documented in this plugin... almost any app today uses push notifications.

Push notifications with CapacitorJS will invariably lead to using firebase.

And unless we missed something, this use of Firebase for Push notifications means you have to use Firebase for GoogleSSO.

And if you have to use Firebase either way... it would help a lot of people by adding this to this projects readme :)

**Comment by j-d-carmichael** [comment]
Yes, we got a little ahead of ourselves. 
It worked in development mode only.

We noticed the addition of the Android OAuth key to google resulted in the AuthScreen status moving to in verification... we can only assume that when this resolves, everything will start working again.

**Comment by j-d-carmichael** [comment]
And vice versa... or any advice from @fullstackduck :)

**Comment by fullstackduck** [comment]
@j-d-carmichael It's been like 3 years since I moved away from Capacitor, @reslear has been maintaining this plugin 😅
PRs and maintainers are welcome. Hope you figure this out.

**Comment by j-d-carmichael** [comment]
@fullstackduck you are the top contributor and the only face I could see on [the parent ](https://github.com/CodetrixStudio) page :D

I can see a published fork by you @reslear but I guess then you took over this one now?

**Comment by reslear** [comment]
@j-d-carmichael fork only for testing - actual code data in this repo. 
Add more info, add reproduction maybe community can help you.
Also PR welcome.

**Comment by sourcer18** [comment]
The same thing happens to me, I need help. A few weeks ago it was working fine.

**Comment by j-d-carmichael** [comment]
@reslear i love that response with gpt hahahaha ❤️❤️ but yea we tried all of that and some... our only conclusion is to wait until the new oauth consent screen is verified... the message they offer is:


> Verification status
>  Verification in progress
> The Trust and Safety team has received your form. They will contact you by email if necessary. The review process can take up to 4–6 weeks. Expect the first email from our Trust and Safety team within 3–5 days. Your last approved consent screen is still in use. Learn more

**Comment by sourcer18** [comment]
Good morning, I have solved it. After discarding everything I came to the conclusion that the sha-1 was not correct. I added the sha-1 that I had in the app on the firebase and that solved it.

**Comment by j-d-carmichael** [comment]
Amazing!  @sourcer18 does this also now work in production mode?

**Comment by sourcer18** [comment]
@j-d-carmichael  Yes, I have generated the application in release mode in android studio after having generated the capacitor and it works correctly.

**Comment by j-d-carmichael** [comment]
Interesting.. and does the verification status look the same for you?

![Screenshot from 2023-03-22 09-52-22](https://user-images.githubusercontent.com/49351986/226866369-8aa4baac-6b0e-41dc-a532-08865963ee71.png)

**Comment by sourcer18** [comment]
I show you a picture of mine @j-d-carmichael 

![image](https://user-images.githubusercontent.com/6040292/226867111-77efa4ca-d1b5-45c0-a419-1fd3346197e6.png)

**Comment by j-d-carmichael** [comment]
Hmm ok.. it seems you have a different status to us.

Translated via google: 

> "Verification is not required
> Your consent screen is displayed, but your app hasn't been reviewed yet. For this reason, other users may not see all of your information, and there are some OAuth permissions that you will not be able to request. More information"
> 

We'll just wait and see...

**Comment by DaveRicho** [comment]
We are getting what I think is a similar message coming up in android studio: 

Sending plugin error: {"save":false,"callbackId":"13544912","pluginId":"GoogleAuth","methodName":"signIn","success":false,"error":{"message":"Something went wrong","code":"10"}}

**Comment by MehediKinesso50200** [comment]
I had the same problem. I had to add debug SHA key in firebase or Google Api console. 

follow this it will be solve
https://stackoverflow.com/questions/49450140/google-signin-api-exception-10

### SUMMARY

- npx cap open android
- click on gradle
- search for gladle signingReport
- copy the SHA key and add to firebase project setting or Google api Console for production need to generate new 
- if you have different production keystore can use the SHA from there as well


<img width="1141" alt="Screenshot 2023-03-26 at 2 58 10 AM" src="https://user-images.githubusercontent.com/103628286/227736332-08d8807a-b530-4f99-9543-0497cd2770f4.png">

<img width="669" alt="Screenshot 2023-03-26 at 2 58 39 AM" src="https://user-images.githubusercontent.com/103628286/227736338-769e719e-78fb-45bb-82ae-75fbbc1f5dff.png">

if you cannot find gladle signingReport press enter regardless because sometime it just dont show up on search result

**Comment by DaveRicho** [comment]
Hi @MehediKinesso50200 , thanks very much for taking the time to explain all of this.

I've tried it, but it was not a sha-1 issue.

The thing that worked for me was to simply delete some lines from my capacitor.config.ts file.

In case this helps any one else, my old broken android capacitor.config.ts file looked like this in part:

```
plugins: {
    ......
    GoogleAuth: {
      scopes: ["profile", "email"],
      serverClientId: "XXXXXXXXXXXXX.apps.googleusercontent.com",
      forceCodeForRefreshToken: true,
      androidClientId: "1:XXXXXXXXXXXX:android:XXXXXXXXXXX",
      iosClientId: "1:XXXXXXXXXXXXX:ios:XXXXXXXXXXXXX",
      clientId: "XXXXXXXXXXXXX.apps.googleusercontent.com",
    },
    .....
  },
```

The fixed version, looks like this (in both samples, I have changed identifiers to protect the innocent!):
```
plugins: {
    ......
    GoogleAuth: {
      scopes: ["profile", "email"],
      serverClientId: "XXXXXXXXXXXXX.apps.googleusercontent.com",
      forceCodeForRefreshToken: true,
    },
    .....
  },
```

So yeah, I just needed to delete the stuff that the Android part of the README.md file made me think we needed.

I think I got a bit confused where the README.md mentioned adding those properties capacitor.config.json, but now that we are on capacitor 4.7, and use a .ts version, seems that we don't need to use the .json at all.

Anyway, I hope my stupidity may help someone else.

Thanks again @MehediKinesso50200, your comment spurred me on to keep digging and trying! Thanks legend!!

**Comment by MehediKinesso50200** [comment]
oh. great. i am very glad you managed to solve the issue. seems like few issues can produce this same error. 
much appreciate that you took your time to post this solution, hope we covered all the bases for error 10.. haha. 
cheers mate! 🥳 🤝
