### ISSUE TITLE
Ability to always choose a Google account from a list

### ISSUE THREAD

**Issue by JohnBuchmann** [CodetrixStudio/CapacitorGoogleAuth#272]
If you log in with one Google account, you are literally not able to switch to another Google account. When logging in, this plugin will use the account you last authenticated with, and you have no way to override this. 

Interestingly, on the web with Firefox (only), it will always prompt you to choose a Google account. But on other browsers, and on Android (I also assume iOS) you cannot. This is a real problem since the user will be forced to forever use only one Google account login. Even if you uninstall and reinstall the mobile app it will auto login with the last account used.

There is a similar post from a couple years ago, but the solution said to signOut() before signing in. But that doesn't solve this issue. Thx!

**Comment by tarangshah19** [comment]
any solution you found?

**Comment by JohnBuchmann** [comment]
No solution yet. But I ended up reverting from Android/iOS to just PWA. This is because on Android things get just way too sluggish. It appears to be a Capacitor with webView issue: https://github.com/ionic-team/capacitor/discussions/3899 
So now as a web app/PWA I am back to using standard google login (I'm using Angular Firebase UI library to make it even easier) and I have no need for CapacitorGoogleAuth

**Comment by tarangshah19** [comment]
any other npm dependancy i am usisng vue js capacitor

**Comment by mirko77** [comment]
It is an issue with the plugin implementation, it is resolving before the signout task is completed.
I will look into it soon

**Comment by mirko77** [comment]
For Android and iOS, you need to set `forceCodeForRefreshToken` to true

**Comment by aljacket** [comment]
I have added the GoogleAuth.signOut() before the signIn and it worked. on Android now alway ask for an account if I press the google login button.

using _vite_, _capacitor 4_, _vue 3_

**Comment by mirko77** [comment]
@aljacket it depends on the device and network speed. I opened a pull request with the fix https://github.com/CodetrixStudio/CapacitorGoogleAuth/pull/288

**Comment by BrayanAngaritaR** [comment]
> 

I think this is the best solution out there for now. I tried it on iOS and it works perfectly :) thank you very much

**Comment by BrayanAngaritaR** [comment]
> any solution you found?

@tarangshah19 

I think this is the best solution out there for now.

Just log out before logging back in. For example:

```
async function signInWithGoogle() {
    await GoogleAuth. signOut();
    const user = await GoogleAuth.signIn();
    authStore. handleLoginGoogle(user); //Optional for store
}
```

I tried it on iOS and it works perfectly :) 

I'm using Vue 3 and Ionic 7
