### ISSUE TITLE
upgrade to Capacitor 5?

### ISSUE THREAD

**Issue by NateWichman** [CodetrixStudio/CapacitorGoogleAuth#279]
hi! thanks for all your hard work! I'm trying to update this to Capacitor 5 and make a PR because I think we are forced to use Capacitor 5 now? I am too stupid tho, so if anyone else knows how to do this please do!

**Comment by NateWichman** [comment]
so I could not figure it out but https://github.com/CodetrixStudio/CapacitorGoogleAuth/pull/277 did and made a pr. I npm installed their repo and just used that instead of this one and everything worked fine I think!

```npm install https://github.com/younited/CapacitorGoogleAuth```

**Comment by reslear** [comment]
https://github.com/CodetrixStudio/CapacitorGoogleAuth/pull/277
