### ISSUE TITLE
Issue when try to register the  plugin on Capacitor.

### ISSUE THREAD

**Issue by jcamposv** [CodetrixStudio/CapacitorGoogleAuth#28]
I have this error when trying to register the plugin, do you know what could be the issue?

```Unhandled Promise rejection: Cannot read property 'GoogleAuth' of undefined ; Zone: <root> ; Task: null ; Value: TypeError: Cannot read property 'GoogleAuth' of undefined```

**Comment by parveenkhtkr** [comment]
Most likely your API key is not configured properly.
