### ISSUE TITLE
Handling different serverClientId values

### ISSUE THREAD

**Issue by letsbelopez** [CodetrixStudio/CapacitorGoogleAuth#29]
I have multiple projects in Firebase each with a different client id. This is to handle different environments. e.g. staging, dev, production.

How would you pass the different client Id values to the capacitor.config.json file?

```
  "plugins": {
    "GoogleAuth": {
      "scopes": ["profile","email"],
      "serverClientId": "XXXXXX.apps.googleusercontent.com"
    }
  }
```

**Comment by parveenkhtkr** [comment]
I am not sure if this falls under the scope of this plugin. The capacitor team needs to come up with a solution to configure different environments.

**Comment by letsbelopez** [comment]
I ended up doing a cp command in the build script to copy over the appropriate config.
