### ISSUE TITLE
Got weird issue, "Error: Something went wrong"

### ISSUE THREAD

**Issue by vincentsartoko** [CodetrixStudio/CapacitorGoogleAuth#296]
I did everything from this video:
https://www.youtube.com/watch?v=GwtpoWZ_78E&ab_channel=SimonGrimm

The web works, but not the app. After clicking the button (GoogleAuth.signIn), it throws bridge error:
```
Error: Something went wrong
    at returnResult ((index):854:32)
    at win.androidBridge.onmessage ((index):829:21)
```

**Comment by ashishasint** [comment]
I've also been getting this issue for a long time in the Android app. If anyone has any idea how to fix this do let us know.

**Comment by vincentsartoko** [comment]
@ashishasint I solved it. Do 100% all the things mentioned in this video:
https://www.youtube.com/watch?v=GwtpoWZ_78E&ab_channel=SimonGrimm
