### ISSUE TITLE
Library migrating

### ISSUE THREAD

**Issue by vincentsartoko** [CodetrixStudio/CapacitorGoogleAuth#297]
Console shows this warning:

> Your client application uses libraries for user authentication or authorization that are deprecated. See the [Migration Guide](https://developers.google.com/identity/gsi/web/guides/gis-migration) for more information.

Any plan for this change?

**Comment by reslear** [comment]
see https://github.com/CodetrixStudio/CapacitorGoogleAuth/issues/202#issuecomment-1831579107
