### ISSUE TITLE
'NSInvalidArgumentException', reason: 'You must specify |clientID| for |GIDSignIn|' on iOS

### ISSUE THREAD

**Issue by gentixyann** [CodetrixStudio/CapacitorGoogleAuth#30]
GoogleAuth works on web, but **iOS does not work.** 

I got uncaught exception when I click the login button of Google.

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'You must specify |clientID| for |GIDSignIn|'
```

I added `REVERSED_CLIENT_ID` as url scheme to `Info.plist` from `GoogleService-Info.plist`

![スクリーンショット 2019-11-24 20 41 39](https://user-images.githubusercontent.com/25972149/69491551-a53c6400-0efb-11ea-843b-b710056f38ae.jpg)

`capacitor.config.json` is like below.
```json
{
  "appId": "com.my.app",
  "appName": "appName",
  "bundledWebRuntime": false,
  "npmClient": "npm",
  "webDir": "www",
  "plugins": {
    "GoogleAuth": {
      "scopes": [
        "profile",
        "email"
      ],
      "serverClientId": "xxxxx.apps.googleusercontent.com"
    }
  }
}
```
`serverClientId ` is  from OAuth 2.0 Client Id of web in Google Cloud Platform

Do you have any idea what am I worng?

**Comment by gentixyann** [comment]
**It solved!!!**

I had checked thoroughly in [your Info.plist](https://github.com/CodetrixStudio/CapacitorGoogleAuth/blob/master/demo/ios/App/App/Info.plist)

**My Info.plist was not correct format.** 
Thank you!

**Comment by nicobytes** [comment]
@gentixyann what is the correct format?
