### ISSUE TITLE
Refresh icon keeps showing

### ISSUE THREAD

**Issue by vincentsartoko** [CodetrixStudio/CapacitorGoogleAuth#302]
Everything works fine on my Capacitor NextJS project, however when calling `GoogleAuth.signIn()`, it always show the refresh icon. Once clicked the icon, Google will then prompt the permission screen for users to click "Allow"
![abc](https://github.com/CodetrixStudio/CapacitorGoogleAuth/assets/56718724/2ea0e074-ef26-4e73-89da-44d53af81d2b)

**Comment by reslear** [comment]
outside the plug-in scope
