### ISSUE TITLE
Cannot retreive access_token. 

### ISSUE THREAD

**Issue by piotrzuzak** [CodetrixStudio/CapacitorGoogleAuth#32]
Hi @parveenkhtkr , 

Could you please give me a hint how to obtain access_token?
I've tried with "scopes": ["profile", "email", "openid"], and "scopes": ["profile", "email"] but without luck. 
I am getting only idToken which is not really useful for me when I'm trying to combine solution with firebase and my external IdP. If it is not possible in this plugin, then please let us know.

Thank you, 
Piotr

**Comment by piotrzuzak** [comment]
For those who don't know => this plugin only gives idToken which means that you have to implement on your backend api piece of code for connecting to google and validating idtoken instead of access token. 

@parveenkhtkr  -> worth to add information about data response into the readme file. Sometimes is really crucial to investigate what's giving you the library that you would like to use. Thank you.

**Comment by parveenkhtkr** [comment]
These three are provided for as long as I remember if you mean something else point me to docs and reopen the issue, please.
```
serverAuthCode
access_token
id_token
```

You can refer to `web.ts` or `user.ts` for any info you desire.

**Comment by Alexandr-Pivovar** [comment]
Hi, when I use web the answer comes in the format:
` {
    id: string;
    email: string;
    name: string;
    familyName: string;
    givenName: string;
    imageUrl: string;
    serverAuthCode: string;
    authentication:  {
        accessToken: string;
        idToken: string;
    };
}`

and I can get accessToken, but when I use this implementation on android, the answer comes in a different format: 
`{
    id: string;
    email: string;
    name: string;
    familyName: string;
    givenName: string;
    imageUrl: string;
    idToken: string;
    serverAuthCode: string;
    authentication:  {
        idToken: string;
    };
}`
we get idToken 2 times and there is no accessToken field.
How do I get accessToken? Maybe there is another way

Thank you,
Alexandr

**Comment by ghonche** [comment]
@Alexandr-Pivovar Did you find any solution for this?
