### ISSUE TITLE
popup_closed_by_user issue on Chrome or Safari

### ISSUE THREAD

**Issue by edshkliaruk** [CodetrixStudio/CapacitorGoogleAuth#325]
I cannot authorise due to this issue:
<img width="536" alt="Screenshot 2023-11-20 at 14 17 47" src="https://github.com/CodetrixStudio/CapacitorGoogleAuth/assets/125352863/a167d09d-1206-42d9-9c2d-b6ea89bee9d2">

I see pop-up with list of account but in the background I see this issue and the next steps do not work.

Someone faced with this issue?

**Comment by yogeshkudikala** [comment]
Facing the same issue

**Comment by edshkliaruk** [comment]
I solved this issue adding `Cross-Origin-Opener-Policy` with `same-origin-allow-popups` value.

**Comment by veneliniliev** [comment]
Exactly! Adding the Cross-Origin-Opener-Policy with the value same-origin-allow-popups is a great solution for this issue. Even Chrome suggests this problem can occur if this policy is not properly configured, as it blocks the window.closed calls. Setting this header ensures the necessary functionality, allowing popup windows to operate smoothly and preventing unwanted blocking of interactions between different windows. Thanks for sharing this solution!
