### ISSUE TITLE
Warnings for deprecated getConfigValue method (iOS)

### ISSUE THREAD

**Issue by piotr-cz** [CodetrixStudio/CapacitorGoogleAuth#334]
When building with XCode, process shows following issues:

CodetrixStudioCapacitorGoogleAuth: 5 issues

> 'getConfigValue' is deprecated: use getConfig() and access config values using the methods available depending on the type.

This method has been deprecated in [Capacitor 4.0.0-beta.0](https://github.com/ionic-team/capacitor/releases/tag/4.0.0-beta.0) in https://github.com/ionic-team/capacitor/issues/5495

**Comment by reslear** [comment]
PR, welcome

**Comment by piotr-cz** [comment]
For reference I found a commits with migration `getConfigValue -> getConfig` in
- `@capacitor/splash-screen` repo: https://github.com/ionic-team/capacitor-plugins/pull/962/files
- `@capacitor/push-notifications` repo: https://github.com/ionic-team/capacitor-plugins/commit/aa623eb8ff88c1fc26d92e72873d659a588cdfc7

Basically usage should be changed like so:

```diff
-(getConfigValue("scopes") as? [String] ?? [])
+(getConfig().getArray("scopes", []) as? [String])

-getConfigValue("forceCodeForRefreshToken") as? Bool
+getConfig().getBoolean("forceCodeForRefreshToken")

-getConfigValue("iosClientId") as? String
+getConfig().getString("iosClientId")
```

However capacitor docs still mention `getConfigValue` as a recommended method for iOS: https://capacitorjs.com/docs/plugins/configuration-values#accessing-configuration-values

**Comment by reslear** [comment]
great reserch, you can try it

**Comment by piotr-cz** [comment]
Android platform has been already migrated to use `getConfig()` method here: [android/src/main/java/com/codetrixstudio/capacitor/GoogleAuth/GoogleAuth.java](https://github.com/CodetrixStudio/CapacitorGoogleAuth/commit/4859f9c11b53476c9247f4697bae5b8b33022870#diff-22dc83f264783374c11c4525c478d5ef66870aec9b829d2a22cb2936bd1bd0e1), even that PR title says that changes relate to iOS
