### ISSUE TITLE
A cross-platform way to retrieve the current user

### ISSUE THREAD

**Issue by Justas-S** [CodetrixStudio/CapacitorGoogleAuth#34]
Currently there is no way to retrieve the authenticated user on app/script startup. This is sort of related to  #26. Could a method be added to retrieve the user? Something similar to this method: https://developers.google.com/identity/sign-in/web/reference#googleauthcurrentuserget

I could submit a PR for web/android but I do not have access to an iOS setup to implement it.

**Comment by parveenkhtkr** [comment]
@Justas-S  v1.5.0 provides a listener for user change.
It's only for web, will be adding support for iOS & Android too.
