### ISSUE TITLE
Capacitor v5 compatibility in 3.4.x

### ISSUE THREAD

**Issue by piotr-cz** [CodetrixStudio/CapacitorGoogleAuth#344]
Version 3.4.0-rc.0 includes commit cdeb575c24bab478a6ce02022a2e22bd69e040a1 which changed text in the readme from *Capacitor 5* to *Capacitor 6*.

This suggest that package requires Capacitor v6, however this version works fine with Capacitor v5 and dependencies still use `@capacitor/*` packages at the `^5` version.

I think that:
- changes in readme from cdeb575c24bab478a6ce02022a2e22bd69e040a1 should be rolled back until peerDependencies have `"@capacitor/core": "^5.0.0 || ^6.0.0"`
- when above is changed, readme should state that this package is compatible with both Capacitor v5 and v6

**Comment by reslear** [comment]
Truth. Can you do PR?
