### ISSUE TITLE
iOS CAP_PLUGIN Macro for GoogleAuth

### ISSUE THREAD

**Issue by wkaskie** [CodetrixStudio/CapacitorGoogleAuth#359]
References: https://github.com/CodetrixStudio/CapacitorGoogleAuth/issues/358

I have the exact same issue as the above reported but I am using a later version of X-Code.

"I am encountering an issue with the CAP_PLUGIN macro when trying to register the GoogleAuth plugin. The plugin registration does not seem to work as expected, and the app fails to compile.
Capacitor : 6.0.0 / GoogleAuth 3.4.0-rc.1 / X-code 15.2

Errors encountered :

Expected identifier or '('
Too few arguments provided to function-like macro invocation
Unknown type name 'CAP_PLUGIN'"

**Comment by seopei** [comment]
I think v3.4.0-rc.2 fixes that. @reslear could you please push a new version to npm?

**Comment by reslear** [comment]
fixed, v3.4.0-rc.3

**Comment by wkaskie** [comment]
Confirmed it's fixed in RC.3
