### ISSUE TITLE
Deprecated API Usage UIWebView APIs

### ISSUE THREAD

**Issue by san4ezgig** [CodetrixStudio/CapacitorGoogleAuth#36]
Could you help please, after adding your package to application, Apple was start warning about deprecated api usage, UIWebView APIs. But in your package files I did not find any mention of this api. Are you using some old version of capasitor / cordova or is the problem different?

**Comment by Aupourbau** [comment]
I m having the same issue. Would be great to have a fix as the deadline of April is coming very soon..

**Comment by ctrengove** [comment]
Also have the issue. I see that Plugin.h has

#import <UIKit/UIKit.h>

at the top, which was presumably put there when the plugin was first bootstrapped. But as far as I can see it can just be commented out.

**Comment by ctrengove** [comment]
So nothing to do with the above comment, of course.

I think the dependency on UIWebView is coming from the version of GoogleSignin in use. This plugin is requiring GoogleSignin version < 5, but version 5 is needed to remove the dependency. See, for example, https://github.com/firebase/FirebaseUI-iOS/issues/771

So the plugin needs to be updated to work with GoogleSignin 5.

**Comment by ctrengove** [comment]
I know have this working with GoogleSignin 5.0.2 (the current version) and will produce a PR once I've confirmed that it does indeed get rid of the AppStore warning.

**Comment by mayur43s** [comment]
It does not as I'm still seeing the user of webview and the app is getting rejected on App Store here's the terminal output with `pod update` 
```
Installing AppAuth (1.3.0)
Installing GTMAppAuth (1.0.0)
Installing GTMSessionFetcher 1.4.0 (source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing GoogleSignIn 5.0.2 (was 4.4.0 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
```
Now when I do `grep -r "UIWeb" .` It gives this output:
```
./Pods/AppAuth/Source/AppAuth.h:    for the auth request. `UIWebView` and `WKWebView` are explicitly *not*
./Pods/AppAuth/README.md:for the auth request. `UIWebView` and `WKWebView` are explicitly *not*
./Pods/GoogleSignIn/CHANGELOG.md:- Supports sign-in via UIWebView rather than app switching to a browser,```

**Comment by ctrengove** [comment]
@mayur43s So I have now had an app accepted in the App Store which incorporates this plugin, so maybe there is something else which is causing the rejection. I note that the references to UIWeb that are listed are all in comments or documentation, not in the actual code.
