### ISSUE TITLE
Capacitor 2.0.0-beta.0 Error

### ISSUE THREAD

**Issue by Raerten** [CodetrixStudio/CapacitorGoogleAuth#37]
https://github.com/ionic-team/capacitor/releases/tag/2.0.0-beta.0
Plugin does'n work with beta version.
I fixed it by change in `android/src/main/res/layout/bridge_layout_main.xml`
`android.support.design.widget.CoordinatorLayout` to `androidx.coordinatorlayout.widget.CoordinatorLayout`

**Comment by parveenkhtkr** [comment]
A PR would be great 🙂
