### ISSUE TITLE
Can not understand auth and afAuth

### ISSUE THREAD

**Issue by PrashantLazzyDevs** [CodetrixStudio/CapacitorGoogleAuth#39]
Kindly let me know about these 2 variables as I am not able to find them.

**Comment by PrashantLazzyDevs** [comment]
I found that these 2 are firebase related objects.
Now I phase another issue that "vendor-es2015.js:40772 ERROR Error: Uncaught (in promise): Error: The identity provider configuration is disabled."

vendor-es2015.js:40772 ERROR Error: Uncaught (in promise): Error: The identity provider configuration is disabled.
    at resolvePromise (polyfills-es2015.js:4147)
    at polyfills-es2015.js:4057
    at polyfills-es2015.js:4073
    at e.b (vendor-es2015.js:99323)
    at Nc (vendor-es2015.js:99326)
    at Jc (vendor-es2015.js:99326)
    at D.push../node_modules/@firebase/auth/dist/auth.esm.js.k.ec (vendor-es2015.js:99325)
    at sc (vendor-es2015.js:99319)
    at ZoneDelegate.invoke (polyfills-es2015.js:3709)
    at Object.onInvoke (vendor-es2015.js:70644)

My question is why use firebase signIn ? Instead of that we can handle it locally as googleUser object has all the required values.
I'm new for this so please help.

**Comment by parveenkhtkr** [comment]
This is probably not the best place to get beginner-level help.

Anyways,
If your app is using firebase then you need to use firebase auth. 
This plugin helps you sign in with Google, usually that would be it, in case of firebase you can pass that token further to Firebase.
From the error message, it seems you haven't enabled the supported provides in your firebase project via firebase console.
