### ISSUE TITLE
Any idea when android will be ready?

### ISSUE THREAD

**Issue by futbotism** [CodetrixStudio/CapacitorGoogleAuth#4]

**Comment by parveenkhtkr** [comment]
Hi, made this plugin for the iOS app I am working on, Android version will be worked on soon along with the plugin in the upcoming month.
However, If you need it earlier lemme know, maybe I can work on it this week.

**Comment by cstsortan** [comment]
I'd love to ship an android app with it too!

**Comment by futbotism** [comment]
Hey @parveenkhtkr that would be great, i don't want to rush you of course, but it seems this plugin is the cleanest and most lightweight solution avail atm.

**Comment by parveenkhtkr** [comment]
Alright, I will try to get the Android version up in a week then. If something changes I will ping here.

**Comment by parveenkhtkr** [comment]
Android is now supported. Plugin update is published. 🎉 
Lemme know if you face any issue.

_ping: @futbotism @cstsortan_

**Comment by futbotism** [comment]
thanks @parveenkhtkr ill look forward to installing this asap
