### ISSUE TITLE
How to use this with ionic?

### ISSUE THREAD

**Issue by BDominik** [CodetrixStudio/CapacitorGoogleAuth#41]
import { Plugins } from '@capacitor/core';
Plugins.GoogleAuth.signIn();
not working in angular.
This plugin was a big waste of time.

**Comment by parveenkhtkr** [comment]
![image](https://user-images.githubusercontent.com/6024312/77849891-97ba2200-71ec-11ea-9d4e-3a87264bd0e3.png)

**Comment by BDominik** [comment]
Nice answer, explains why the plugin works perfectly.
