### ISSUE TITLE
v2.0.0 doesn't work with androix appcompat

### ISSUE THREAD

**Issue by thibaud-sanchez** [CodetrixStudio/CapacitorGoogleAuth#43]
The version of google auth dependency you are using is using support v4 fragment, and if I use it with Capacitor 2 and androidx, it crash.

```
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/FragmentActivity;
04-07 15:17:02.335  1690  1786 E AndroidRuntime:        at com.google.android.gms.auth.api.signin.internal.zzh.zzc(Unknown Source:1)
04-07 15:17:02.335  1690  1786 E AndroidRuntime:        at com.google.android.gms.auth.api.signin.GoogleSignInClient.getSignInIntent(Unknown Source:20)
04-07 15:17:02.335  1690  1786 E AndroidRuntime:        at com.codetrixstudio.capacitor.GoogleAuth.GoogleAuth.signIn(GoogleAuth.java:54)
04-07 15:17:02.335  1690  1786 E AndroidRuntime:        ... 7 more
```

I think you should use the latest version, it works fine on my project now :

https://github.com/CodetrixStudio/CapacitorGoogleAuth/blob/d6e73f9fdb790c8a1e0afa10dbe0e749e88ca76e/android/build.gradle#L46

replace with : 
`implementation 'com.google.android.gms:play-services-auth:18.+'`

Source : https://developers.google.com/android/guides/setup

**Comment by parveenkhtkr** [comment]
Thanks for reporting @thibaud-sanchez
