### ISSUE TITLE
Ability to force email selection to get refreshtoken

### ISSUE THREAD

**Issue by thibaud-sanchez** [CodetrixStudio/CapacitorGoogleAuth#44]
I need to get a refreshtoken eachtime I use googleAuth,  and I prefer that the plugin show me the email selection prompt eachtime.
I've edited your plugin to force it, by replacing `googleSignInBuilder.requestServerAuthCode(clientId)` with `      .requestServerAuthCode(clientId,true)`
https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInOptions.Builder#requestServerAuthCode(java.lang.String,%20boolean)

Maybe you should set it to true by default, or add a parameter into capacitor config.
I haven't done a PR because I don't know if it is the same way for iOS.

Thank you for this great plugin

**Comment by parveenkhtkr** [comment]
Thanks, up in 2.1.0
