### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by nicobytes** [CodetrixStudio/CapacitorGoogleAuth#45]
I try use that plugin in Android but when I use the return is `Something went wrong`

![Screen Shot 2020-04-09 at 1 36 06 PM](https://user-images.githubusercontent.com/7611944/78934114-60633500-7a78-11ea-8984-cc68c0bdede1.png)

**Comment by thibaud-sanchez** [comment]
You can look this pinned issue, it's a developer/config problem : 
https://github.com/CodetrixStudio/CapacitorGoogleAuth/issues/15

**Comment by asiermusa** [comment]
I have the same problem! I created a new firebase project and then I created a new oAuth client for Android. Y generated SHA1  fingerprint, and all was ok. In the browser it works ine but when I launch de app with Android Studio I have the same message as you.

I have read a lot of messages about this problem but I dont solve yet.

Thanks

**Comment by asiermusa** [comment]
I'm sorry...I solved the problem following this steps: https://github.com/CodetrixStudio/CapacitorGoogleAuth/issues/15

Thanks!
