### ISSUE TITLE
Google SignIn Error 12500

### ISSUE THREAD

**Issue by muaviaUsmani** [CodetrixStudio/CapacitorGoogleAuth#47]
Something has changed over the past 2-3 days that's now causing this problem. Last week this was working fine for me. I've updated to version 2.0.1 (though I was already on version 2.0.0) but to no avail.

<img width="1027" alt="Screenshot 2020-04-13 at 2 59 47 PM" src="https://user-images.githubusercontent.com/4430221/79112280-a3cee380-7d97-11ea-9fc4-49834ba97689.png">

**Comment by thibaud-sanchez** [comment]
You must update your base play service to 18 I think : https://github.com/CodetrixStudio/CapacitorGoogleAuth/issues/43

**Comment by muaviaUsmani** [comment]
Its already using the play service 18. notice the line below highlighted one (`com.google.android.gms:play-services-auth@@18.0.0:9`)

**Comment by muaviaUsmani** [comment]
Other probable causes of error 12500 have to do with settings from OAuth screen but that's not the case because its working fine for iOS and web. So the issue is with android only.

**Comment by thibaud-sanchez** [comment]
The plugin use the auth version 18, but seems that the base service is in version 17 (check the first stack lines) and maybe  they're not compatibles. Maybe you have another plugin that use version 17 somewhere

**Comment by muaviaUsmani** [comment]
I think 17 is the latest base version we have.(?) Looking at this https://developers.google.com/android/guides/setup

**Comment by thibaud-sanchez** [comment]
Yes, my bad. Maybe, you can try to update to 17.2.1 ? 
This is the only modification between 2.0.0 and 2.0.1, so I think the problem is a compatibility problem between versions of play services

**Comment by muaviaUsmani** [comment]
That wasn't it. Version updated, but error remains the same.

<img width="1071" alt="Screenshot 2020-04-20 at 1 29 09 PM" src="https://user-images.githubusercontent.com/4430221/79730938-04679e80-830b-11ea-9d5d-10a67c978be8.png">

**Comment by thibaud-sanchez** [comment]
It could be a problem with your project support email address or sha-1 you used that is not register in google play console : 
https://stackoverflow.com/questions/47632035/google-sign-in-error-12500

**Comment by muaviaUsmani** [comment]
the client ID was generated from developers' console not firebase, so didn't really have to insert any support email there, nor should sha-1 be the issue since we're using web client ID for android, no?

**Comment by thibaud-sanchez** [comment]
You must create an android credential with your sha1 despite you use web credential (I already had this problem).

**Comment by muaviaUsmani** [comment]
Got it. What location and filename should I put that in? Asking since that's not mentioned in documentation.

**Comment by thibaud-sanchez** [comment]
Don't use it, just create it on the console, and try it.
Did you put the web clientid in your android string.xml and into capacitor config ?

**Comment by muaviaUsmani** [comment]
this works now. creating the android key in console helped.
