### ISSUE TITLE
You must specify |clientID| for |GIDSignIn in IOS

### ISSUE THREAD

**Issue by nicobytes** [CodetrixStudio/CapacitorGoogleAuth#48]
I follow the steps:

1. Make sure you have GoogleService-Info.plist with CLIENT_ID
2. Add REVERSED_CLIENT_ID as url scheme to Info.plist

But in IOS doesn't work and the show this error:

```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'You must specify |clientID| for |GIDSignIn|'
```

![Imgur](https://i.imgur.com/5OtHbpB.png)

That is the locations for `GoogleService-Info.plist` and `Info.plist`

![Imgur](https://i.imgur.com/w0twtL8.png)

My `GoogleService-Info.plist` have the `CLIENT_ID` and `REVERSED_CLIENT_ID`

![Imgur](https://i.imgur.com/ZW18o7j.png)

My `Info.plist` have the `REVERSED_CLIENT_ID as an url scheme:

![Imgur](https://i.imgur.com/r2dEYc5.png)

My `capacitor.config.json`:

![Imgur](https://i.imgur.com/aAiWH08.png)

I did check https://github.com/CodetrixStudio/CapacitorGoogleAuth/issues/30 but doesn't work

My environment:

```
@capacitor/cli 2.0.1
@capacitor/android 2.0.1
@capacitor/ios 2.0.1
@capacitor/core 2.0.1

 Found 3 Capacitor plugins for ios:
    @codetrix-studio/capacitor-google-auth (2.0.1)
    @rdlabo/capacitor-facebook-login (2.0.2)
    capacitor-apple-login (0.0.6)
```

**Comment by nicobytes** [comment]
My error was copy and page `GoogleService-Info.plist` in folder the correct form is open Xcode and add file with drag a dog.

**Comment by fzamperin** [comment]
Thanks a lot @nicobytes, saved my life
