### ISSUE TITLE
Errors when build on Xcode 

### ISSUE THREAD

**Issue by georgefam** [CodetrixStudio/CapacitorGoogleAuth#49]
<img width="486" alt="Screen Shot 2020-04-23 at 3 20 55 pm" src="https://user-images.githubusercontent.com/8745172/80062060-2a44ab80-8576-11ea-990c-4c414a778ca4.png">

I'm getting attached screen shot errors when I try to build the project in Xcode.

any recommendation, how I can fix it ? Thanks

Using
    "@codetrix-studio/capacitor-google-auth": "^2.1.0",

Update:
 I have downgrade into version 2 and Xcode build successfully , Thanks

**Comment by matheusdavidson** [comment]
I'm also getting these errors while using `@capacitor/core@2.0.1` and `@codetrix-studio/capacitor-google-auth@2.1.0`, had to downgrade to `@capacitor/core@2.0.0-beta.1` and `@codetrix-studio/capacitor-google-auth@2.0.1`

**Comment by matheusdavidson** [comment]
Strange thing is that with latest capacitor and plugin it works in android(but only after doing android x migration, at least it works)

**Comment by stefanotauriello** [comment]
Same problem with 2.1.0

**Comment by thibaud-sanchez** [comment]
I've identified the problem.
This is a line feed problem, you can edit the Plugin.swift if you need the force auth code functionnality

https://github.com/CodetrixStudio/CapacitorGoogleAuth/pull/50

**Comment by parveenkhtkr** [comment]
![image](https://user-images.githubusercontent.com/6024312/80824853-ddf40e00-8bfc-11ea-9611-833bc33cdf3a.png)
