### ISSUE TITLE
Get code for server side use

### ISSUE THREAD

**Issue by macdja38** [CodetrixStudio/CapacitorGoogleAuth#5]
In the iOS flow it would be nice to be able to get a one time code to send to the server so it can take action on behalf of the user. It shouldn't be more than a couple lines of additional code from what I can see [here](https://developers.google.com/identity/sign-in/ios/offline-access) and would greatly increase the usability of this library, at least in my case.

**Comment by macdja38** [comment]
I'm not familiar with swift but getting it working (not well though) is as simple as:

In the init
```
        guard let serverClientId = dict["SERVER_CLIENT_ID"] as? String else {return}
        GIDSignIn.sharedInstance().serverClientID = serverClientId;
```

In the signIn Callback
```
            "serverAuthCode": user.serverAuthCode,
```

**Comment by parveenkhtkr** [comment]
Hey, will add it.
Thanks for the snippet.

**Comment by macdja38** [comment]
No problem, also for documenting it, google's documentation doesn't say this but user.serverAuthCode seems to be null sometimes if the user has already signed in, calling signOut then signIn again will give you a code reliably, in my testing at least.

This library doesn't yet implement signOut but I've made a pr for it here https://github.com/CodetrixStudio/CapacitorGoogleAuth/pull/6 .

**Comment by parveenkhtkr** [comment]
Sign out added for iOS (ty) & Web in [0.1.0](../releases/tag/0.1.0)

**Comment by parveenkhtkr** [comment]
@macdja38  ServerAuthCode added to iOS & Web in [0.3.0](../releases/tag/0.3.0)
