### ISSUE TITLE
Cannot retrieve access_token (updated)

### ISSUE THREAD

**Issue by Stanly1995** [CodetrixStudio/CapacitorGoogleAuth#53]
Hi, when I use web, the answer comes in the format:
` {  
    id: string;  
    email: string;  
    name: string;  
    familyName: string;  
    givenName: string;  
    imageUrl: string;  
    serverAuthCode: string;  
    authentication:  {  
        accessToken: string;  
        idToken: string;  
    };  
}`  

and I can get accessToken, but when I use this implementation on android, the answer comes in a different format: 
`{  
    id: string;  
    email: string;  
    name: string;  
    familyName: string;  
    givenName: string;  
    imageUrl: string;  
    idToken: string;  
    serverAuthCode: string;  
    authentication:  {  
        idToken: string;  
    };  
}`
we get idToken 2 times and there is no accessToken field.
How do I get accessToken? Maybe there is another way

Thank you,
Alexandr

_Originally posted by @Alexandr-Pivovar in https://github.com/CodetrixStudio/CapacitorGoogleAuth/issues/32#issuecomment-638057611_

**Comment by gabsgasps** [comment]
me too

**Comment by gabsgasps** [comment]
**the accessToken is missing in the native code**
https://github.com/CodetrixStudio/CapacitorGoogleAuth/blob/5d2165d0856328891f48c5c6fe383541f42edb1b/android/src/main/java/com/codetrixstudio/capacitor/GoogleAuth/GoogleAuth.java#L80

**web code contains accessToken:**
https://github.com/CodetrixStudio/CapacitorGoogleAuth/blob/5d2165d0856328891f48c5c6fe383541f42edb1b/src/web.ts#L114

**Comment by aboutroots** [comment]
Hi, seems like analogous plugin for cordova is also working the same way. I think that this  [comment](https://github.com/EddyVerbruggen/cordova-plugin-googleplus/issues/337#issuecomment-280097897) sums it up. 

I'm probably going to implement the exchange of `serverAuthCode` to `access_token` manually on my backend, as per [google docs](https://developers.google.com/identity/sign-in/android/offline-access).

**Comment by mghcs87** [comment]
any solution? to get accessToken on android.

**Comment by mghcs87** [comment]
any solution? :(

**Comment by aboutroots** [comment]
> any solution? :(

Hi @mghcs87 , sorry for the slow reply. I managed to take care of serverAuthCode on backend and it works just fine. I simply exchange it for access_token. Unfortunately I didn't find the solution for `access_code` on android, but now I don't feel the need to do it. My Ionic code looks similar to:
```
import '@codetrix-studio/capacitor-google-auth';
import { Plugins } from '@capacitor/core';
// ...
const GoogleUser = await Plugins.GoogleAuth.signIn();
server_auth_code = GoogleUser.serverAuthCode;

// then I pass this code to backend.
```

And backend python code:
```
def get_token_from_gapi(code):
    """Exchange serverAuthCode for access_token"""
    data = {
        "code": code,
        "client_id": CLIENT_ID,
        "client_secret": CLIENT_SECRET,
        "grant_type": "authorization_code",
    }
    r = requests.post("https://oauth2.googleapis.com/token", data=data)
    if r.status_code < 200 or r.status_code >= 300:
        raise HTTPError("Authorization using serverAuthCode failed.")
    token = r.json()["access_token"]
    return token
```
Please note that CLIENT_ID and CLIENT_SECRET are your credentials for web application, not for android (since this happens on backend). 
Good luck 🔥

**Comment by mghcs87** [comment]
Hi @aboutroots, Thank you very much for your answer, currently I solve this problem with the `cordova-plugin-googleplus` plugin that @martindongo refers to, but it would be nice to be able to use it on android from `CapacitorGoogleAuth`. Once again Thank you for your time.

**Comment by Niravpatel129** [comment]
> > any solution? :(
> 
> Hi @mghcs87 , sorry for the slow reply. I managed to take care of serverAuthCode on backend and it works just fine. I simply exchange it for access_token. Unfortunately I didn't find the solution for `access_code` on android, but now I don't feel the need to do it. My Ionic code looks similar to:
> 
> ```
> import '@codetrix-studio/capacitor-google-auth';
> import { Plugins } from '@capacitor/core';
> // ...
> const GoogleUser = await Plugins.GoogleAuth.signIn();
> server_auth_code = GoogleUser.serverAuthCode;
> 
> // then I pass this code to backend.
> ```
> 
> And backend python code:
> 
> ```
> def get_token_from_gapi(code):
>     """Exchange serverAuthCode for access_token"""
>     data = {
>         "code": code,
>         "client_id": CLIENT_ID,
>         "client_secret": CLIENT_SECRET,
>         "grant_type": "authorization_code",
>     }
>     r = requests.post("https://oauth2.googleapis.com/token", data=data)
>     if r.status_code < 200 or r.status_code >= 300:
>         raise HTTPError("Authorization using serverAuthCode failed.")
>     token = r.json()["access_token"]
>     return token
> ```
> 
> Please note that CLIENT_ID and CLIENT_SECRET are your credentials for web application, not for android (since this happens on backend).
> Good luck 🔥

I'm making the same call as you through postman and on my local client, I seem to be getting this error: 
```{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}```

Google seems to behave pointed out that it could be the token being invalid, is there any setting you changed for your client to allow this API call to go through?

**Comment by Vitiumartis** [comment]
I have the same problem.

Any solution for this plugin?

**Comment by kavitha306** [comment]
Same issue here, any plans to address this issue?

**Comment by mihajlon97** [comment]
Any news? Same bug here!

**Comment by bCliks** [comment]
the issue were fixed & waiting to merge 
https://github.com/CodetrixStudio/CapacitorGoogleAuth/pull/56

**Comment by JohnCarlo29** [comment]
Alternative you can create a patch using `https://www.npmjs.com/package/patch-package` and replace the existing code provided by this PR `https://github.com/CodetrixStudio/CapacitorGoogleAuth/pull/56`
