### ISSUE TITLE
what is the option argument that needs to be passed in GoogleAuth.signIn()?

### ISSUE THREAD

**Issue by aditbharadwaj** [CodetrixStudio/CapacitorGoogleAuth#54]
![google error](https://user-images.githubusercontent.com/6751554/84678486-b3aca480-af4d-11ea-81fc-527826b21be0.PNG)
as u can see this is error iam facing right now ? what is the value argument option required by the method?
Ionic info below
```
Ionic:

   Ionic CLI                     : 5.2.7 (C:\Users\Adit\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.6
   @angular-devkit/schematics    : 9.1.6
   @angular/cli                  : 9.1.6
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.2.0
   @capacitor/core : 2.2.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.11.3
   OS     : Windows 10
```

**Comment by masimplo** [comment]
It is just a wrong interface. `signIn` takes no arguments. If you want to get it to work before the author fixes this, Just pass `null` to make typescript happy and you are good for now.

**Comment by aditbharadwaj** [comment]
> It is just a wrong interface. `signIn` takes no arguments. If you want to get it to work before the author fixes this, Just pass `null` to make typescript happy and you are good for now.

so passing null will fix it for now good i can proceed to complete this part of login now thank you for reply.

**Comment by aditbharadwaj** [comment]
the inter face is soo wrong bcoz it doesnt even have the logout parameter and busted signin ? how is anyone able to signout ?
![signout](https://user-images.githubusercontent.com/6751554/85837204-61714c00-b7b5-11ea-8a43-8d570571656b.PNG)
how is this interface still not fixed ? or am i accessing something wrong ?
