### ISSUE TITLE
MainActivity add(GoogleAuth.class); 

### ISSUE THREAD

**Issue by TravBradfield** [CodetrixStudio/CapacitorGoogleAuth#60]
Simple question. I have added to the init method in MainActivity like the docs suggest. However, I'm not sure what the import for `add(GoogleAuth.class);` is? Please let me know what the import is? Thanks.

`import <Something>`
`
this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
  add(GoogleAuth.class);
}});
`

**Comment by csurbier** [comment]
Hi,

Why did you close the issue without comment ? I have the same issue even after removing/adding plugin again and done the npx cap sync or update. 
Compilation failed.

![Selection_006](https://user-images.githubusercontent.com/2241990/89205822-993f9080-d5b8-11ea-8a7e-150baddef14e.png)


Thanks for your help

**Comment by csurbier** [comment]
ok got it. For those having same error, you need to import 

import com.codetrixstudio.capacitor.GoogleAuth.GoogleAuth;

it should be nice to mention it in the documentation.
