### ISSUE TITLE
ios14 issues?

### ISSUE THREAD

**Issue by DaveRicho** [CodetrixStudio/CapacitorGoogleAuth#69]
Is anyone else having problems in ios14? Was working perfectly for us prior to 14, but the pop up browser seems to get closed as soon as it opens now. It is still working fine in a browser for us.

**Comment by mikeyyyzhao** [comment]
@DaveRicho are you seeing this bug in xcode console as well? 

<img width="604" alt="Screen Shot 2020-12-11 at 9 40 39 PM" src="https://user-images.githubusercontent.com/4956032/101978522-5fd3fd00-3c0a-11eb-9099-8f4372080ea5.png">

Here's how I'm calling login (using react)
```
onClickLogin() {
    Plugins.GoogleAuth.signIn().then((googleUser) => {
      console.log('googleUser', googleUser);
    }).catch((error)=>{
      console.log('User interrupted the login process', error);
    });
  }
```

**Comment by DaveRicho** [comment]
@mikeyyyzhao, I'm using ionic angular (with @angular/fire for firebase) and have a slightly different ios problem.

inside of my async function, this next line never resolves (googleUser never returns or errors, it just hangs waiting for ever...):

let googleUser = await Plugins.GoogleAuth.signIn(null) as any;

As I said above, I don't have the problem on web or Android.

**Comment by mikeyyyzhao** [comment]
Not sure if this will help your issue but uninstalling firebase helped me solve my issue above

**Comment by DaveRicho** [comment]
@mikeyyyzhao, thanks for the suggestion. I just upgraded to the mnost recent firebase version ("firebase": "^8.2.1"), but am still having the same issue.

Did you reinstall firebase (after removing) and it then worked for you? (or have you stopped using firebase?).

Thanks again and happy new year!!

**Comment by mikeyyyzhao** [comment]
We've actually stopped using Firebase all together. Esp with firebase's version upgrade (7 to 8), generally, it feels like a lot of things are broken so we decided to go a more native route. Happy new year to you as well!

**Comment by LeCoupa** [comment]
> @mikeyyyzhao, I'm using ionic angular (with @angular/fire for firebase) and have a slightly different ios problem.
> 
> inside of my async function, this next line never resolves (googleUser never returns or errors, it just hangs waiting for ever...):
> 
> let googleUser = await Plugins.GoogleAuth.signIn(null) as any;
> 
> As I said above, I don't have the problem on web or Android.

Yes same for me, the code hangs waiting forever. Does someone know how to fix the issue?

**Comment by webdog-rich** [comment]
@DaveRicho I believe the plugin is hanging due to the fact that it does not return anything when it restores a previous sign in. I have just submitted a PR to fix this.

https://github.com/CodetrixStudio/CapacitorGoogleAuth/pull/194
