### ISSUE TITLE
Add custom scopes

### ISSUE THREAD

**Issue by macdja38** [CodetrixStudio/CapacitorGoogleAuth#7]
Scopes can be added in the load() method by assigning to the scopes property of `.sharedInstance()` 

For example
```
GIDSignIn.sharedInstance().scopes = ["https://www.googleapis.com/auth/userinfo.email", "https://www.googleapis.com/auth/userinfo.profile"]
```

I'm not sure what the best way to load this data from a plist is, or if their's a better way to store it but it would be very useful addition, for my use case at least, to customize the scopes available.

**Comment by parveenkhtkr** [comment]
@macdja38 this is published in version [0.2.0](../releases/tag/0.2.0)

**Comment by macdja38** [comment]
Thanks, looks good.

I'm not sure how much I like how many places stuff needs to be configured in though.

**Comment by parveenkhtkr** [comment]
The default configuration is kept as is on purpose, so one can reference the Official Google Docs.
The non-default configuration goes into `capacitor.config.json`, this will be the place for all future configuration like #5 

Hmm, how do I put it?
This plugin (and capacitor for that matter) aims to build upon the native experience without getting in your way ever.

Say you wanna integrate Firebase or other Google service after a while, the `plist` is already there for you.
If each plugin follows their own way then you will end up copying the same configuration multiple times for each Google Service.

I hope this makes sense. I will be open to improve upon this in the future in case it becomes a problem.
