### ISSUE TITLE
Native authentication ignored over web implementation

### ISSUE THREAD

**Issue by PaulCombal** [CodetrixStudio/CapacitorGoogleAuth#76]
I cannot get this plugin to show the native UI anymore. I'm using the Quasar framework and Android 9.

My code (in a component):
```
import 'app/src-capacitor/node_modules/@codetrix-studio/capacitor-google-auth'
import {Plugins} from '@capacitor/core'
....

// I tried this
      Plugins.GoogleAuth.signIn()
        .then(googleUserCb)
        .catch(e => console.error('Could not authenticate with Google: ', e))
// and this to better match the doc with th same outcome
        (async () => {
          let googleUser = await Plugins.GoogleAuth.signIn();
          console.log(googleUser)
        })();

```

When this code is executed, I can see in the stack trace that the GoogleAuthWeb version is executed. Instead of showing me the native "Login with Google UI", it opens Chrome to prompt me to select my account.

Here is a screenshot of my "Remote device" inspect view if that can bring in more informations:
![image](https://user-images.githubusercontent.com/5382590/104848082-a2f94e00-58e3-11eb-89bd-953e0c323bf6.png)

Do you think this can be in relation to this issue: https://github.com/ionic-team/capacitor/issues/4056 ? 

Thanks for any input

EDIT: it works as intended when using http instead of https, more on this when I'll have time.

**Comment by PaulCombal** [comment]
This seems to only happen when using HTTPS with a local CA. Using HTTP even with a local domain works as intended. For now I'll stick to HTTP for the debug environment.

**Comment by codemickey78** [comment]
@PaulCombal How did you change your dev environment to use to http? I'm using Ionic Angular with Capacitor 3.
