### ISSUE TITLE
How to get basic profile or email?

### ISSUE THREAD

**Issue by atmosuwiryo** [CodetrixStudio/CapacitorGoogleAuth#8]
Try with ionic, build for native ios.
Successfully sign-in, the return value didn't contain any user information.

Anyhow to retrieve it?

**Comment by parveenkhtkr** [comment]
Currently, it does not return any user info.
I will be publishing an update today (will ping you) then you will have access to user information.

**Comment by atmosuwiryo** [comment]
Awesome. Thank you

**Comment by parveenkhtkr** [comment]
@atmosuwiryo user info is now exposed in [1.1.0](../releases/tag/1.1.0)
