### ISSUE TITLE
Stuck on webview loading

### ISSUE THREAD

**Issue by epicshaggy** [CodetrixStudio/CapacitorGoogleAuth#80]
When I first implemented this it worked great, no tweaking needed.  I came back to it after a week or so and I was getting API exception 10.  I fixed that and now after I select the account it brings up this webview and continues loading.
![image](https://user-images.githubusercontent.com/50883345/106616180-a297be80-6543-11eb-9286-526916d9336b.png)

**Comment by epicshaggy** [comment]
Solved it, sharing in case anyone runs into the same issue.  Turns out that setting `"forceCodeForRefreshToken" : true` was causing the problem.  At first it worked fine but then out of nowhere it started bringing up this blank webview.  setting it to false fixed the issue.  To always bring up the account selection screen I just call `signOut()` before every `signIn()` call.

**Comment by maxime1jacquet** [comment]
Brillant ! Thank you !

**Comment by narcis-sy** [comment]
Another possible issue, which took me 8 hours of research. Your auth consent screen is set on internal. Publish it, even without verification, and it will start working again. 

This setting is in your google cloud console:
![D408397C-38CF-4DB6-915A-2A3FD487BD5F](https://user-images.githubusercontent.com/67704105/119027565-28366180-b9af-11eb-89c1-e92f4bd21f92.png)

It also only affects some devices and not other. Our was a One Plus.


It’s a known bug:
See comments here:
https://stackoverflow.com/questions/65853630/android-app-with-google-drive-api-stucks-after-choosing-an-account-why/65900011#65900011

https://issuetracker.google.com/issues/178183308?pli=1
