### ISSUE TITLE
[Capacitor Plugin Error] - GoogleAuth - signIn - Unable to serialize plugin ...

### ISSUE THREAD

**Issue by atmosuwiryo** [CodetrixStudio/CapacitorGoogleAuth#9]
Got Error, and no data retrieved:
`[Capacitor Plugin Error] - GoogleAuth - signIn - Unable to serialize plugin response as JSON.Ensure that all data passed to success callback from module method is JSON serializable!
`

If i commented the code for imageUrl in Plugin.swift(line:88), the error vanished, and got the user data.
`// "imageUrl": user.profile.imageURL(withDimension: 100),`

**Comment by parveenkhtkr** [comment]
Thanks @atmosuwiryo, fixed in [1.1.1](../releases/tag/1.1.1)
