### ISSUE TITLE
Capacitor 3 targets iOS 12 but this plugin targets 11

### ISSUE THREAD

**Issue by AVatch** [CodetrixStudio/CapacitorGoogleAuth#91]
When trying to compile with a capacitor 3 project I get the following error 

`Compiling for iOS 11.0, but module 'Capacitor' has a minimum deployment target of iOS 12.0`

**Comment by kaimallie** [comment]
Solved it temporary by updating **IPHONEOS_DEPLOYMENT_TARGET** from 11.0 to 12.0 at: 
`ios/App/Pods/Pods.xcodeproj/project.pbxproj`

**Comment by reslear** [comment]
use please
https://www.npmjs.com/package/@codetrix-studio/capacitor-google-auth/v/3.0.0
