### ISSUE TITLE
Capacitor 3 questions

### ISSUE THREAD

**Issue by Yuripetusko** [CodetrixStudio/CapacitorGoogleAuth#98]
Hi, I am a little bit clueless on scope of work that is required to make this capacitor 3 compatible, otherwise I would contributed with a PR

But can anyone please tell me how compatible this plugin is and what needs to be done if it isn't. Also if this plugin is still maintained at all. 

Thanks

**Comment by SantiagoIlli** [comment]
Hi!

Are you sure that this Plugin does not support capacitor 3? Last time i checked the last official version it's still 2 (i'm using 2.4.7)

Anyway, i would like to know as well if this plugin is still being maintained.

**Comment by Yuripetusko** [comment]
> Hi!
> 
> Are you sure that this Plugin does not support capacitor 3? Last time i checked the last official version it's still 2 (i'm using 2.4.7)
> 
> Anyway, i would like to know as well if this plugin is still being maintained.

It doesn't look like, and few PRs that support capacitor 3 are not looked at for over a month sadly :(

**Comment by michalsisak** [comment]
Also wondering about the status of the repo. Capacitor v3 is in release candidate and it should land soon! 
I am worried looking at the number of issues and PR's open though.

**Comment by Yuripetusko** [comment]
I actually switched to https://github.com/baumblatt/capacitor-firebase-auth which has capacitor 3 PR and branch and npm tag #next which works well for google auth / facebook and apple

**Comment by SantiagoIlli** [comment]
Seems like the way to go!

Thanks @Yuripetusko

**Comment by vanessag** [comment]
Any update on capacitor 3 support for this plugin? It doesn't seem to work.

**Comment by reslear** [comment]
@parveenkhtkr please release new versions with last commit changes) thank you

**Comment by instasunrise** [comment]
You need to change one line in the file node_modules/@codetrix-studio/capacitor-google-auth/dist/esm/definitions.d.ts from @capacitor/core to @capacitor/cli and the library works in version 3

**Comment by reslear** [comment]
@instasunrise but need author release for working in appflow build,) ping @parveenkhtkr :)

**Comment by fr3fou** [comment]
Any news?

**Comment by reslear** [comment]
@Yuripetusko @SantiagoIlli @michalsisak @vanessag @instasunrise @fr3fou 
i'm fork this repo, add new features, testing on web and ios,  and publish to npm, if need Capacitor 3 support welcome )
https://www.npmjs.com/package/@reslear/capacitor-google-auth

**Comment by reslear** [comment]
not actual, use please https://www.npmjs.com/package/@codetrix-studio/capacitor-google-auth/v/3.0.0
